---
- block:
    - name: ensure specified locales are present on RedHat 7 distributions
      ansible.builtin.command: >-
        localedef
        -i {{ item | langcode | quote }}
        -f {{ item | encoding | quote }}
        {{ item | encoding2lower | quote }}
      changed_when: false
      loop: "{{ locales_locales_present }}"

    - name: ensure specified locales are absent on RedHat 7 distributions
      ansible.builtin.command: >-
        localedef
        --delete-from-archive {{ item | langcode | quote }}
        -f {{ item | encoding | quote }}
        {{ item | encoding2lower | quote }}
      changed_when: false
      loop: "{{ locales_locales_absent }}"
  when:
    - ansible_distribution_major_version is version('7', '<=')

- name: configure locales
  ansible.builtin.template:
    src: locale.conf.j2
    dest: "{{ locales_conf_file }}"
    owner: root
    group: root
    mode: 0644
