---
- name: Install requireds packages
  loop: "{{ locales_required_packages | flatten }}"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present

- name: Manage language-packs packages
  when:
    - locales_language_packages is defined
    - locales_language_packages is iterable
    - locales_language_packages | length > 0
  loop: "{{ locales_language_packages | flatten }}"
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: "{{ item.state }}"

- name: "Load tasks for configure locales for {{ ansible_os_family }}"
  ansible.builtin.include_tasks:
    file: "tasks/sub-tasks/locales_{{ ansible_os_family | lower }}.yml"

- name: Load tasks for configure console keymap
  ansible.builtin.include_tasks:
    file: tasks/sub-tasks/keymap.yml
