---
- name: install requireds packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ locales_required_packages | flatten }}"

- name: manage language-packs packages
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ locales_language_packages | flatten }}"

- name: "load tasks for configure locales for {{ ansible_os_family }}"
  ansible.builtin.include_tasks:
    file: "tasks/sub-tasks/locales_{{ ansible_os_family }}.yml"

- name: load tasks for configure console keymap
  ansible.builtin.include_tasks:
    file: tasks/sub-tasks/keymap.yml
